---
## Install ruby & epel repo
- name: install dependency packages
  yum: pkg={{ item }} update_cache=yes
  with_items:
    - ruby
    - epel-release

## Install riemann
- name: install Riemann packages
  yum:
    name: https://github.com/riemann/riemann/releases/download/0.2.13/riemann-0.2.13-1.noarch.rpm
    state: present

## Copy Riemann config
- name: copy riemann config to /etc/riemann/
  template: 
    src: config/riemann.config.j2
    dest: /etc/riemann/riemann.config

## Config java tmp folder
- name: copy riemann sysconfig to /etc/sysconfig
  template:
    src: config/riemann-sysconfig.j2
    dest: /etc/sysconfig/riemann

## Check /tmp/riemann.service exists
- name: check /tmp/riemann.service exists
  stat:
    path: /tmp/riemann.service
  register: tmpriemann_existd

## Check  /run/systemd/generator.late/riemann.service exists
- name: check /run/systemd/generator.late/riemann.service exists
  stat:
    path:  /run/systemd/generator.late/riemann.service
  register: riemann_svc_existd

## Generate start/stop script
- name: generate start/stop script
  command: "/usr/lib/systemd/system-generators/systemd-sysv-generator"
  run_once: true
  when: tmpriemann_existd.stat.exists == false

- name: copy start/stop script to /systemd folder
  command: "/usr/bin/cp /tmp/riemann.service  /run/systemd/generator.late/"
  run_once: true
  when: riemann_svc_existd.stat.exists == false

