---
## Install ruby & epel repo
- name: install dependency packages
  yum: pkg={{ item }} update_cache=yes
  with_items:
    - ruby
    - epel-release

## Install riemann
- name: install Riemann packages
  yum:
    name: https://github.com/riemann/riemann/releases/download/0.2.13/riemann-0.2.13-1.noarch.rpm
    state: present

## Copy Riemann config
- name: copy riemann config to /etc/riemann/
  template: 
    src: riemann.config.j2
    dest: /etc/riemann/riemann.config

## Config java tmp folder
- name: copy riemann sysconfig to /etc/sysconfig
  template:
    src: riemann-sysconfig.j2
    dest: /etc/sysconfig/riemann

## Check /tmp/riemann.service exists
- name: check /tmp/riemann.service exists
  stat:
    path: /tmp/riemann.service
  register: tmpriemann_existd

## Check  /run/systemd/generator.late/riemann.service exists
- name: check /run/systemd/generator.late/riemann.service exists
  stat:
    path:  /run/systemd/generator.late/riemann.service
  register: riemann_svc_existd

## Generate start/stop script
- name: generate start/stop script
#  command: "/usr/lib/systemd/system-generators/systemd-sysv-generator;/usr/bin/cp /tmp/riemann.service  /run/systemd/generator.late/"
  command: "/usr/lib/systemd/system-generators/systemd-sysv-generator"
  run_once: true
  when: tmpriemann_existd.stat.exists == false

- name: copy start/stop script to /systemd folder
  command: "/usr/bin/cp /tmp/riemann.service  /run/systemd/generator.late/"
  run_once: true
  when: riemann_svc_existd.stat.exists == false

## Setting iptables to porting L4 metrics to realserver port
- iptables:
    table: nat
    destination: "{{ vip }}"
    destination_port: "{{ vip_port }}"
    chain: PREROUTING
    protocol: "{{ portocol }}"
    jump: REDIRECT
    to_ports: "{{ real_server_port }}"
    comment: redirect "{{ vip }}" port "{{ vip_port }}" traffic to port "{{ real_server_port }}"

- name: Check LB setting in rc.local
  shell: grep "{{ real_server_port }}" /etc/rc.local
  register: LB_result

- name: add LB setting to rc.local
  lineinfile: dest=/etc/rc.local line="iptables -t nat -A PREROUTING -p {{ portocol }} -d {{ vip }} -j REDIRECT --dport {{ vip_port }} --to-port {{ real_server_port }} -m comment --comment \"redirect \"{{ vip }}\" port \"{{ vip_port }}\" traffic to port \"{{ real_server_port }}\"\""
  when: LB_result.stdout != ""


## Start Riemann
- name: start Riemann
  service:
    name: riemann
    state: started
    enabled: yes
