---
# Keepalived config
smtp_server: 127.0.0.1
notification_email:
  - juan.gilpin@redcypress.com.tw
  - izek.chen@redcypress.com.tw
  - fann.wu@redcypress.com.tw
notification_email_from: test@redcypress.com.tw

keepalived_bind_interface: eno16780032
auth_pass: graphite
keepalived_vip: 10.62.4.240

LB: 
  - {protocal: "UDP", VIP_Port: "12000", realserver: ["10.62.4.158 12001", "10.62.4.158 12002","10.62.4.158 12003","10.62.4.158 12004","10.62.4.158 12005" ] }
