---
# base setting
NIC_name: eno16780032

# Carbon
carbon_metrics_prefix: prod.sys.fp.carbon
carbon_metric_interval: 60


# Relay, relay_method:consistent-hashing / rules
relay_method: rules
relay_factor: 1

destinations:
  - 127.0.0.1:2014:1

# for relay_method: consistent-hashing
relay_instance:
  - {instance: "1",line_port: "2013",pinckle_port: "2014"}
  - {instance: "2",line_port: "2023",pinckle_port: "2024"}
  - {instance: "3",line_port: "2033",pinckle_port: "2034"}
  - {instance: "4",line_port: "2043",pinckle_port: "2044"}
  - {instance: "5",line_port: "2053",pinckle_port: "2054"}
  - {instance: "6",line_port: "2063",pinckle_port: "2064"}
  

# for relay_method: rules
relay_rule:
  - {metric_name: "stats.gauges.MGS_", pattern: '^stats.gauges.MGS_.*\..*', destinations: "tng1522:2004, tng1522:2004", continue: "False"}
  - {metric_name: "stats.timers.MGS_", pattern: '^stats.timers.MGS_.*\..*', destinations: "tng1522:2004, tng1522:2004", continue: "False"}
  - {metric_name: "stats_counts.MGS_", pattern: '^stats_counts.MGS_.*\..*', destinations: "tng1522:2004, tng1522:2004", continue: "False"}
  - {metric_name: "stats.gauges.Eclipse", pattern: '^stats.gauges.Eclipse\..*', destinations: "tng1522:2004, tng1522:2004", continue: "False"}
  - {metric_name: "stats.gauges.Veyron", pattern: '^stats.gauges.Veyron\..*', destinations: "tng1522:2004, tng1522:2004", continue: "False"}
  - {metric_name: "stats.timers.Veyron", pattern: '^stats.timers.Veyron\..*', destinations: "tng1522:2004, tng1522:2004", continue: "False"}
  - {metric_name: "stats_counts.Veyron", pattern: '^stats_counts.Veyron\..*', destinations: "tng1522:2004, tng1522:2004", continue: "False"}
  - {metric_name: "stats.gauges.api", pattern: '^stats.gauges.api\..*', destinations: "tng1522:2004, tng1522:2004", continue: "False"}
  - {metric_name: "stats.timers.api", pattern: '^stats.timers.api\..*', destinations: "tng1522:2004, tng1522:2004", continue: "False"}
  - {metric_name: "stats_counts.api", pattern: '^stats_counts.api\..*', destinations: "tng1522:2004, tng1522:2004", continue: "False"}
  - {metric_name: "default", pattern: '', destinations: "tng1520:2014, tng1520:2024, tng1520:2034, tng1520:2044, tng1520:2054, tng1521:2014, tng1521:2024, tng1521:2034, tng1521:2044, tng1521:2054", continue: "False"}

# Storage retentions
storage_schema:
  - {metric_name: "carbon", pattern: '^carbon\.', retentions: '60s:90d'}
  - {metric_name: "default", pattern: '.*', retentions: '1m:1d'}
