---
## Prepare epel repo
- name: install epel repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name : install python 3.4 and pip 3 packages
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python34
    - python34-pip
