---
## Install telegraf
- name: install telegraf packages
  yum: 
    name: https://dl.influxdata.com/telegraf/releases/telegraf-1.3.1-1.x86_64.rpm
    state: present
## Copy telegraf internal & other config to /etc/telegraf/telegraf.d/
- name: Copy telegraf config to /etc/telegraf/telegraf.conf
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
- name: Copy telegraf internal to /etc/telegraf/telegraf.d/
  copy: 
    src: telegraf_internal.conf
    dest: /etc/telegraf/telegraf.d/
- name: Copy telegraf statsd & riemann config to /etc/telegraf/telegraf.d/
  template:
    src: telegraf_statsd_riemann.conf.j2
    dest: /etc/telegraf/telegraf.d/telegraf_statsd_riemann.conf
## Start Telegraf
- name: Start telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes
