---
## Install telegraf
- name: install telegraf packages
  yum: 
    name: https://dl.influxdata.com/telegraf/releases/telegraf-1.3.1-1.x86_64.rpm
    state: present
## Copy telegraf internal & other config to /etc/telegraf/telegraf.d/
- name: Copy telegraf config to /etc/telegraf/telegraf.conf
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
- name: Copy telegraf internal to /etc/telegraf/telegraf.d/
  copy: 
    src: telegraf_internal.conf
    dest: /etc/telegraf/telegraf.d/
- name: Copy telegraf statsd & riemann config to /etc/telegraf/telegraf.d/
  template:
    src: telegraf_statsd_riemann.conf.j2
    dest: /etc/telegraf/telegraf.d/telegraf_statsd_riemann.conf

- iptables:
    table: nat
    destination: "{{ vip }}"
    destination_port: "{{ vip_port }}"
    chain: PREROUTING
    protocol: udp
    jump: REDIRECT
    to_ports: "{{ real_server_port }}"
    comment: redirect "{{ vip }}" port "{{ vip_port }}"  traffic to port "{{ real_server_port }}"  

- name: copy rc.local to /etc/
  copy:
    src: rc.local.j2
    dest: /etc/rc.local

## start telegraf
- name: start telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes
