---
## Install telegraf
- name: install telegraf packages
  yum: 
    name: https://dl.influxdata.com/telegraf/releases/telegraf-1.3.1-1.x86_64.rpm
    state: present

## Copy telegraf internal & other config to /etc/telegraf/telegraf.d/
- name: Copy telegraf config to /etc/telegraf/telegraf.conf
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
- name: Copy telegraf internal to /etc/telegraf/telegraf.d/
  template: 
    src: telegraf_internal.conf.j2
    dest: /etc/telegraf/telegraf.d/telegraf_internal.conf.j2
- name: Copy telegraf kafka & graphite config to /etc/telegraf/telegraf.d/
  template:
    src: telegraf_kafka_graphite.conf.j2
    dest: /etc/telegraf/telegraf.d/telegraf_kafka_graphite.conf

## Start Telegraf
- name: Start telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes
