---
## copy confluent repo
- name: copy confluent repo to /etc/yum.repos.d/
  copy:
    src: repo/confluent.repo
    dest: /etc/yum.repos.d/confluent.repo

## Install kafka, zookeeper
- name: install Confluent platform
  yum: pkg={{ item }} update_cache=yes
  with_items:
    - confluent-platform-oss-2.11

## Ensure zookeeper directory exist
- name: Ensure zookeeper data dir exist
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory

- name: Ensure zookeeper log dir exist
  file:
    path: "{{ zookeeper_log_dir }}"
    state: directory

- name: Ensure zookeeper version-2 dir exist
  file:
    path: "{{ zookeeper_data_dir }}/version-2" 
    state: directory

## Zookeeper config
- name: copy zookeeper config to /etc/kafka/
  template:
    src: zookeeper/zookeeper.properties.j2
    dest: /etc/kafka/zookeeper.properties

- name: copy zookeeper id file to zookeeper data folder
  template:
   src: zookeeper/myid.j2
   dest: "{{ zookeeper_data_dir }}/myid"

## Zookeeper systemctl script
- name: copy zookeeper systemctl start/stop script to /usr/lib/systemd/system
  copy:
    src: systemctl/confluent-zookeeper.service
    dest: /usr/lib/systemd/system/confluent-zookeeper.service

- name: copy zookeeper start script to /usr/bin/
  template:
    src: systemctl/zookeeper-server-start.j2
    dest: /usr/bin/zookeeper-server-start

## Kafka config
- name: copy kafka config to /etc/kafka
  template:
    src: kafka/server.properties.j2
    dest: /etc/kafka/server.properties

## Kafka systemctl script
- name: copy kafka systemctl start/stop script to /usr/lib/systemd/system
  copy:
    src: systemctl/confluent-kafka.service
    dest: /usr/lib/systemd/system/confluent-kafka.service

- name: copy kafka start script to /usr/bin/
  template:
    src: systemctl/kafka-server-start.j2
    dest: /usr/bin/kafka-server-start

## Kafka internal metrics library
- name: copy kafka export metrics to graphite library to /usr/share/java/kafka/
  copy:
    src: lib/kafka-graphite-1.0.4.jar
    dest: /usr/share/java/kafka/kafka-graphite-1.0.4.jar

- name: copy kafka metrics collector library to /usr/share/java/kafka/
  copy:
    src: lib/metrics-graphite-2.2.0.jar
    dest: /usr/share/java/kafka/metrics-graphite-2.2.0.jar

## Start firewalld 
- service:
    name: firewalld
    state: started

## zookeeper port
- firewalld:
    port: 2181/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 2888/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 3888/tcp
    permanent: true
    state: enabled

## Kafka Port
- firewalld:
    port: 9092/tcp
    permanent: true
    state: enabled

