---
# Keepalived config
smtp_server: 127.0.0.1
notification_email:
  - juan.gilpin@redcypress.com.tw
  - izek.chen@redcypress.com.tw
  - fann.wu@redcypress.com.tw
notification_email_from: test@redcypress.com.tw

keepalived_bind_interface: eno16780032
auth_pass: graphite
keepalived_vip: 0.0.0.0
check_script_folder: /var/tmp


LB: 
  - {protocal: "UDP", VIP_Port: "12000", realserver: ["{{ ansible_eno16780032.ipv4.address }} 12001", "{{ ansible_eno16780032.ipv4.address }} 12002","{{ ansible_eno16780032.ipv4.address }} 12003","{{ ansible_eno16780032.ipv4.address }} 12004","{{ ansible_eno16780032.ipv4.address }} 12005" ] }
