---
## Install telegraf
- name: install telegraf packages
  yum: 
    name: https://dl.influxdata.com/telegraf/releases/telegraf-1.3.1-1.x86_64.rpm
    state: present
## Copy telegraf internal & other config to /etc/telegraf/telegraf.d/
- name: Copy telegraf config to /etc/telegraf/telegraf.conf
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
- name: Copy telegraf internal to /etc/telegraf/telegraf.d/
  copy: 
    src: telegraf_internal.conf
    dest: /etc/telegraf/telegraf.d/
- name: Copy telegraf statsd & riemann config to /etc/telegraf/telegraf.d/
  template:
    src: telegraf_statsd_riemann.conf.j2
    dest: /etc/telegraf/telegraf.d/telegraf_statsd_riemann.conf

- iptables:
    table: nat
    destination: "{{ vip }}"
    destination_port: "{{ vip_port }}"
    chain: PREROUTING
    protocol: "{{ portocol }}"
    jump: REDIRECT
    to_ports: "{{ real_server_port }}"

## Also write iptable rule to /etc/rc.local
- name: Check LB setting in rc.local
  shell: cat /etc/rc.local |grep "{{ real_server_port }}" |wc -l
  register: LB_result

- name: add LB setting to rc.local
  lineinfile: dest=/etc/rc.local line="iptables -t nat -A PREROUTING -p {{ portocol }} -d {{ vip }} -j REDIRECT --dport {{ vip_port }} --to-port {{ real_server_port }}"
  when: LB_result.stdout == "0"
        
