---
## Install telegraf
- name: install telegraf packages
  yum: 
    name: https://dl.influxdata.com/telegraf/releases/telegraf-1.3.1-1.x86_64.rpm
    state: present

# Ensure log folder exist
- name: Ensure log dir exist
  file:
    path: "{{ logfolder }}"
    state: directory
    owner: telegraf
    group: telegraf
    recurse: true

## Copy telegraf internal & other config to /etc/telegraf/telegraf.d/
- name: Copy telegraf config to /etc/telegraf/telegraf.conf
  copy:
    src: config/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
- name: Copy telegraf internal to /etc/telegraf/telegraf.d/
  copy: 
    src: config/telegraf_internal.conf
    dest: /etc/telegraf/telegraf.d/
- name: Copy telegraf statsd & riemann config to /etc/telegraf/telegraf.d/
  template:
    src: config/telegraf_statsd_riemann.conf.j2
    dest: /etc/telegraf/telegraf.d/telegraf_statsd_riemann.conf

## Create telegraf collector firewall rule
- name: Create telegraf collector zone
  command: firewall-cmd --permanent --new-zone telegrafcollector

- firewalld:
    zone: telegrafcollector
    port: 12000
    permanent: true
    state: enabled
