---

- name: install percona repo packages
  yum: 
    name: http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    state: present

- name: install percona-xtradb packages
  yum: pkg={{ item }} update_cache=yes
  with_items:
    - Percona-XtraDB-Cluster-56
    - expect

## Copy Mysql config
- name: Copy mysql config to /etc/
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

## For Bootstrap server
- name: Copy bootstrap init script to "{{ mysql_data_dir }}"
  template:
    src: init_bootstrap_server.sh.j2
    dest: "{{ mysql_data_dir }}/init_bootstrap_server.sh"
    mode: 0755
  when:  (first_install  == true) and (ansible_fqdn in mysql_bootstrap_server)

- name: init bootstrap DB
  command: /bin/sh "{{ mysql_data_dir }}/init_bootstrap_server.sh"
  when:  (first_install  == true) and (ansible_fqdn in mysql_bootstrap_server)

## For other server
- name: Copy other server init script to "{{ mysql_data_dir }}"
  template:
    src: init_mysql_server.sh.j2
    dest: "{{ mysql_data_dir }}/init_mysql_server.sh"
    mode: 0755
  when:  (first_install  == true) and (ansible_fqdn not in mysql_bootstrap_server)

- name: init bootstrap DB
  command: /bin/sh "{{ mysql_data_dir }}/init_mysql_server.sh"
  when:  (first_install  == true) and (ansible_fqdn not in mysql_bootstrap_server)

