---

## Install Percona XtraDB
- name: install percona repo packages
  yum: 
    name: http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    state: present

- name: install percona-xtradb packages
  yum: pkg={{ item }} update_cache=yes
  with_items:
    - Percona-XtraDB-Cluster-56
    - expect

# Ensure mysql data dir exist
- name: Ensure mysql data dir exist
  file:
    path: "{{ mysql_data_dir }}"
    state: directory

## Copy Mysql config
- name: Copy mysql config to /etc/
  template:
    src: config/my.cnf.j2
    dest: /etc/my.cnf

## For Bootstrap server
- name: Copy bootstrap init script to /var/tmp/
  template:
    src: script/init_bootstrap_server.sh.j2
    dest: /var/tmp/init_bootstrap_server.sh
    mode: 0755
  when:  (first_install  == true) and (ansible_fqdn in mysql_bootstrap_server)

- name: init bootstrap DB
  command: /bin/sh /var/tmp/init_bootstrap_server.sh
  when:  (first_install  == true) and (ansible_fqdn in mysql_bootstrap_server)

## For other server
- name: Copy non bootstrap server init script to /var/tmp
  template:
    src: script/init_mysql_server.sh.j2
    dest: /var/tmp/init_mysql_server.sh
    mode: 0755
  when:  (first_install  == true) and (ansible_fqdn not in mysql_bootstrap_server)

- name: init non bootstrap DB
  command: /bin/sh "/var/tmp/init_mysql_server.sh"
  when:  (first_install  == true) and (ansible_fqdn not in mysql_bootstrap_server)

