---
# Carbon
data_dir: "/lv_data01/graphite/storage/whisper"
log_dir: "/lv_data01/graphite/storage/log"

# Graphite web
secret_key: nTbtgMFfWALx4Vj3
memcached_host: 127.0.0.1
memcached_port: 11211

mysql_grphite_password: graphiteV9qnyCuhmYhqVD6N

cluster_servers:
  - tng1522:80
  - tng1523:80
 
