---
## Install Memcached
- name: install memcached packages
  yum: pkg={{ item }} update_cache=yes
  with_items:
    - memcached
    - python-memcached

- name: Copy memcached config to /etc/sysconfig
  copy:
    src: memcached
    dest: /etc/sysconfig/memcached

## Start memcached
- name: Start memcached service
  service:
    name: memcached
    state: started
    enabled: yes
